<Project Sdk="MSTest.Sdk/4.4.0">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AwesomeAssertions" Version="9.6.0" />
		<PackageReference Include="Bogus" Version="35.6.5" />
		<PackageReference Include="NSubstitute" Version="6.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ef.Poc.Application.Contracts\Ef.Poc.Application.Contracts.csproj" />
		<ProjectReference Include="..\Ef.Poc.Application\Ef.Poc.Application.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
		<PackageReference Update="Microsoft.Testing.Extensions.TrxReport" Version="2.4.0" />
		<PackageReference Update="MSTest.TestAdapter" Version="4.4.0" />
		<PackageReference Update="MSTest.TestFramework" Version="4.4.0" />
	</ItemGroup>

</Project>
