<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
		<UserSecretsId>4ecddccc-948a-44af-899f-a7e7370a991a</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Knx.Falcon.Sdk" Version="6.4.8671" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
        <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
    </ItemGroup>
</Project>
