<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Common\Poc.Common.Spectre\Poc.Common.Spectre.csproj" />
		<ProjectReference Include="..\Poc.Ef.Application\Poc.Ef.Application.csproj" />
		<ProjectReference Include="..\Poc.Ef.Infrastructure\Poc.Ef.Infrastructure.csproj" />
		<ProjectReference Include="..\Poc.Ef.Persistence\Poc.Ef.Persistence.csproj" />
	</ItemGroup>
</Project>
