services:
  yugen-home-budget-aspnet:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/home/app/.microsoft/usersecrets
      - ${HOME}/.aspnet/https/:/https/

  yugen-home-budget-sql:
    environment:
      MSSQL_PID: "Developer"
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password1"
    # volumes:
    #   - ./.volumes/sql/data:/var/opt/mssql/data
    #   - ./.volumes/sql/log:/var/opt/mssql/log
    #   - ./.volumes/sql/secrets:/var/opt/mssql/secrets