<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Poc.Ef.Domain.Shared\Poc.Ef.Domain.Shared.csproj" />
    <ProjectReference Include="..\Poc.Ef.Domain\Poc.Ef.Domain.csproj" />
  </ItemGroup>

</Project>
