<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ef.Poc.Domain.Shared\Ef.Poc.Domain.Shared.csproj" />
    <ProjectReference Include="..\Ef.Poc.Domain\Ef.Poc.Domain.csproj" />
  </ItemGroup>

</Project>
