name: poc-docker
services:

  poc-docker-aspnet:
    container_name: poc-docker-aspnet
    entrypoint: ["dotnet", "Poc.Docker.Aspnet.dll"]      
    build:
      context: ..
      dockerfile: Poc.Docker.Aspnet/Dockerfile    
      args:
        - PROJECT=Poc.Docker.Aspnet     
    # depends_on:
    #   - poc-docker-sql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - poc-network

  poc-docker-sql:
    container_name: poc-docker-sql
    hostname: poc-docker-sql
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports:
      - "1433:1433"
    networks:
      - poc-network

networks:
  poc-network:
    driver: bridge
    name: poc-network
