services:

  poc-docker-aspnet: 
    environment:
      # - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8443
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=Password@12345#
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/localhost.pfx
      - ConnectionStrings__MsSql=Server=poc-docker-sql;User ID=sa;Password=Password@12345#;Encrypt=True;Trust Server Certificate=True;Connection Timeout=10;
      - MyVar1=MyVar11
      - MyVar2__MyVar2=MyVar22
      - MyVar3:MyVar3=MyVar33
    ports:
      # - "9999:8080"
      - "9999:8443"
    volumes:
      - ${APPDATA}/microsoft/UserSecrets/:/home/app/.microsoft/usersecrets
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    # - ../.volumes/data:/data
    
  poc-docker-sql:
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "Password@12345#"
    volumes:
    - ../.volumes/sql/data:/var/opt/mssql/data
    - ../.volumes/sql/log:/var/opt/mssql/log
    - ../.volumes/sql/secrets:/var/opt/mssql/secrets